language: node_js

node_js:
  - 8

deploy:
  - provider: script
    script: "./bin/deploy.sh"
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    - SERVERLESS_FRAMEWORK_VERSION=1.28
    - secure: sTOl4rsy6AQ6g3W46whK8PB+CQoJPQ1RoUch3imsyhdecWvA01k0K8d0gZyu6S+6BrhZhJZhxPruPKcvQmOIEkKOo/o+GkgWeHaMRED4VmRTddFvBFrOD6ieIbRjbcIUlth/i8T5w/iNxxJQ3A12w/B0Z+ERcLukYW7VRQRpFTu0GkCOhbBS86lsuzn3HpdeHipctrAbjbSIk++gqi7WbyluE7YAvQf6bFX0kBmKXcEixAxHZ0kH3llUu7MoqHTRHPklvWZM6GlBw6SsovnbcIxYV2ppzuYV6wDE5z06hH0LfPZ4GQDRZxe36oYZmRuSFErMAmpcSyUxiEiGOKh5Yn2ovKjXC3/8EPJAOIMtb9pDc6n82pYjQsS9fCXP7DZCXZvjTT5YAiQZzRke/Y9rOYTr231hU9ZrobpU+UBJ4IiREdQ0iCptYqYlNjpUZz4rgjIBsv2GFBSmqr02An7fXXMNs1aY1YLME9bAi7/I1hCWg6m5SAkXBcB55msmTUb49iXlI4RNLxU+Cmxa2ruWmynnxRhQ8mBf2zpLvDs7vGSIPh/1mNBawxt/LbD18mVgInWit5kv+YLmFcseAHYL3nwCflqY9H0kgFnzKP2hObz6f1uya47jSm58z2iNhDCQEd+iBKXPOAWTXlqj9iDiw7YBrZnv2ybTj2JIO56vC78=
    - secure: hGBlRC7q9hfkj+U+DYZke5VQBAKX5hDQLj5JVxLe/P2IxDoHc3gNbHppNbyXW7aOcis+59RVckUZO1h65fN1dldooafTknjqxYUW6AcvWa3w1XlAuV9Kpr8NClgHqRaFXZ2NvgJdxjo2mZaZDmKheYi6RxeUcRsO1lWUyZWrBDyxF6+4/LcgR6N2uHKxs0VqIk5SsDKNi/cIvpgCeMf6ggtuQI0Z2/j9yw6O6bE+UgKYojWCRCMZphSSkD0nCNUaHAElig9HJ8Hn3shU4BnfMUTEIf2dg6677v4dhhxmfjOyXG5SqUQS5n1WZdtTA/vGxsia/5G9i9C0lcyHefFwFWrJBk1C2L8r6QrD7eg3rieCgWyCS2aw5W/PwEpbk1ctG88I6NDXs2oLQXoOQIVFeZo+WjPWTu5DcPBm+lF4v0JQuplgxqahlrknPEu8la8padrvoBufnkLJMk6g7FZ7QmXHflV66Tvu7mVSEl3ipUhh0HgbxrXxUmx6Nig9UAmdTSRtz+iJbeLD+vm8jhoNV4W0fNsRqB/CYaTyPbIpp5xEd/8IcwHFZZCyjNQCNIfUqfnk9GYCU5elWdInWBmr3h/cd56OHvDYVnrWlYGYPVCa8dxBoYgLdzYZOySQ53pLEDq7FE0QMEgwwFTR6naxxGic0krGYjVrr0WXCJreuEs=
