service:
  name: interview-mock-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2

functions:
  getUser:
    handler: handlers/get-user.handler
    events:
      - http:
          method: get
          path: /user
          cors: true

  getPortfolios:
    handler: handlers/get-portfolios.handler
    events:
      - http:
          method: get
          path: /{userId}/portfolios
          cors: true

  getPortfolioPositions:
    handler: handlers/get-portfolio-positions.handler
    events:
      - http:
          method: get
          path: /portfolio/{portfolioId}/positions
          cors: true
